# WARNING EXAMPLE FILE

# version: "3.0"

# services:
#   node-torrent:
#     ports:
#       - 3333:3333
#       - 51413:51413
#       - 51413:51413/udp
#     build: .
#     environment:
#       - PASSWORD=password
#       - USER_NAME=max
#       - MOVIE_DIR=/movies
#       - SERIES_DIR=/series
